<a href="https://colab.research.google.com/github/RajeshNaidu1/DataScience/blob/main/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#full and empty numpy
import numpy as np
a= np.empty([2,2])
b= np.full((2,2),5,dtype=int)
print(a)
print(b)

[[2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323]]
[[5 5]
 [5 5]]


In [ ]:
#numpy full of zeros and ones
import numpy as np
a= np.zeros((3,3))
print(a)
b= np.ones((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#checking wheter numpy has specified row
import numpy as np
a= np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print([4,5,6] in a.tolist())
print([1,2,4] in a.tolist())

True
False


In [ ]:
#reverse numpy
import numpy as np
a= np.array([1,2,3,4,5])
reverse= a[: : -1]
print(reverse)

[5 4 3 2 1]
